language: node_js
node_js:
- "5"
install:
- npm install
before_script:
  - npm install -g gulp
script:
  - gulp test
sudo: false
deploy:
 provider: lambda
 access_key_id: $DEV_AWS_KEY
 secret_access_key: $DEV_AWS_SECRET
 function_name: tc-tags-api
 region: 'us-east-1',
 handler: 'index.handler',
 role: $LAMBDA_AWS_ROLE
 timeout: 5
 memory_size: 248
 on: 
   branch: dev

env:
  matrix:
    - CXX=g++-4.8
  global:
    # DEV_AWS_KEY
    - secure: BwUf0WljxuSU11iUhhff+BpZbFIsgHdr8wVEzsUjdgrMVyNjh5bSOjbDWXKV9b+9ZOONd2retgBD1JAdCkmEnaZczR9GvcBgQFSHKUHcNQZc2FwzjZcVeWK0Jeo9ga1UUi8UttEIZJ60LXatOp+a9hkSWxJcvGAt8VhA1oPFvwtdoqoe3BkQ6CNqkjLHfTGBj66PbMKOLVautK1BVAOcwA0jHr8R9Ge4sMtLl6YhGiZcdNqexN/Wpbg7b/lLyJbb3LV3teIQ1M0HuRujLmiD23vW9oLdbtSXuL+SZGQuMf8Mu+X+7OdONV+l/64i1OHDLtjbtw/b6mRElROYpaTn/Az6S3t9Jj3Y2PJWeT/rrlwL8XUOT6nBlfydBpHoa5NJNeIF0HvkE0g9XYxCLF3xhst3eUYQYtht/vn4MxOYYFBN83Pn2vyfv79N6JZjDRCwTmiVHgdCyPQvHii3pyknD7WPRpKJ2GcP503zp0swouZwd0RdLL70vnJWD+Cig97buHGXu1+tefDmS4Rzfa7vRSnSuuIgN3VPScJ7K1eKmGtN87v69Nxcdy3Oy3YV94mu+xpL/MUNvNKpdAvliLn37B5Cq+yU99hEdwewQe0Bz3LFG3AyXOJx15nAIkCC1u7xBOycdwGBSQE4oL7/Sg5Jdx6oB3EpTO2INXw/vlN/cuQ=
    # DEV_AWS_SECRET
    - secure: dbPLpXEaY278eWfm3yrHzmj2y2iD6CgYud3xDMjVDoyXcFOzk8ib+AYIkNp2g+y+lnI0QRn2A/fk9Vln4/XJ7gbNY+n7u9tYEQUXf4/DfJMkXwgi1ORG2e2yxH+nanJaKDXXEtfEw7nosDzscXVSJsh1doB7vEAViZl14Ri+61/9nKuGUSU8li7cgPZPvDNIUgfTvaLDA/qLiSronmf4pFu8PTmFpII+XV7GoJdS11TYahXQOmT+7Xgg8RSu9jpNQAFFN6WordH7hUz0068msEfYUF9RUXpgelNzRZCEG2vOyMXTr3+CEiv1lV9IOZeusQrjOnlGsIyiFn8Mt5XEr0J5lSNsDooiLW4fj06shUFlvPHuWalF+gVr1sw6luq3EZP7ky/WtlX7R/fdo7UhkaaxNbdpRBY4K15gesjUVYyz/3/liMvJ3cU+g/OFniKrsr7pWOvHgJ422iRUhmWOi86rZbEUU/iDBVQvbgyOF9MkQaGL/gqUc3Z47tGC4s2aI8eMw4GLpgCEVVJW54u67obD7rhecCQOdw36fPHYwJ9lJNju3yYGGXduNgk7H27A0V9Fu54wq1IlCRh7PndL7A8cOrSaLlNisAwqYaZZeXo0zBqzCgt1cdWSgVTT1J4XQCD3Vx9ICmj0fc2QmrqOrT4L8dsY78oBPkwpRAvaOtw=
    # LAMBDA_AWS_ROLE
    - secure: jjih1/o1b1j0lbWgiGMzsccQXeUtcD46y2tUhMxErnPdK9UahP/caOGHEqt7mpiRtzWFV5bT1hL0JUMCTV5oQOMS/uuBAzjK8Ek+lJnAulDJ8MD3SbFUOvrrpy6SV18s1W81fXIOifsEl+nJ0SXLqfAFC5FgWZt/4tiMHm9nUpt97dy8h2i3K0I9vkkMIe/oR8u+5t4V/s8XOXpkAHixY2ruRVf1jIfcw2lwWx3x7vdAgocvYiquJlgqlLIxPhA7wqI5T8ABrHDDdEcO6yEvbDv2hdsqn/56PzHf97/iyV77Afb5rbs200sFcNVZ34qdRDKBXCOm9bP2KLlF3Z6L01CjeTqhyj+BfHDPbzz38hgPxSoUpYe0IgbcWj1F5FnS1mUtwooEIfAZpnrJZ8B8FjllsLMtMkmkttwnkqgDDA0qXTCROaAwzT+MIY0/AQZEwQH2TZAZwpF9U/qUwyfMzpgeyI1lWevDx0mif3ek4XHYGoy3St4yTQka2ZJsFjkxMWK2Smr+/jl4/KutldHRN9ce3CU7j8Se9YvxbEhAAwDdrPgS4fftd1+cLVtkuTCId5m4AruR4q06DZtaIM4llhEeAiDtSAi5VrkRCNYC6kbf88ut3WVmqQwB6rW78gd4Lm25ZZmnzXBM7CR36kioPmMn3rA1L1Mvajj142X2pN8=
notifications:
  slack:
    secure: PMGlpdBoRzMlIjCsPWdXJ1wf550b+mpX0x44ggGWNL7ErpNebfyqIbXf4VJXYQDmhVJt31ygDaxTtj8XwZJlbvQjE6WGHU26KvL/efGJJL5EmgFD8LDBFpsbn49PyoZuVOTbSzqP8d8WCCPo4oBvX2r2Q2Ixh/tUx7i4Bcv0XwNpWAR75v1Yq/NftEI48k2GcI3oHqmuEgLHdP93k1rCUM4sBsgkr4PCltZfoE2AWlF6wY59w/oFiKj4FwycY8QjJZa/zbSQq1B/9QD7n4YBY4QjVv3LmjshEiQv1HGo2rNLV+/BB5ZoQ6JEH9h+seduHNTF+mkToKbJ2YjDERLlqLFYWVQKXTqFkSdYuknguJ3uOfXFaGtPDSqTRljE6WW6UDIJi9lDpxFHjH2q848/2O03RKtYeFKJWNbVb7Q2PWTBFxx6OurYra+tbUAorQiYmAQxd0vJY+qzGIDJZIQ8yDE4C10heOhfRyU8wJSKF3xJUKKWVGfBuHivFBZOETFSg0uVBcJnsXRcErvEQz0LuKaZfP81bIokcKUGxum/xyp9mYhYqWDvIj31RUhDMiRxXTPe9PhW0mlOtRG7tm2+8G08exHPSfONSV2IPUtlQt4j2/+I22ncOwtsm6yZzXXbDjoMR2sCHIyJj3lVECOqAnCfNJ6Q0CNJ93LqxKSHdFU=